apiVersion: apps/v1
kind: Deployment                                  # Type of the kubernetes resource
metadata:
  name: nginx-integrity-sum                   # Name of the Kubernetes resource
  labels:
    app: app-nginx-hasher-injector
spec:
  replicas: 1                                     # Number of pods to run at any given time
  selector:
    matchLabels:
      app: app-nginx-hasher-injector                 # This deployment applies to any Pods matching the specified label
  template:                                       # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                                     # The labels that will be applied to all of the pods in this deployment
        app: app-nginx-hasher-injector
        main-process-name: nginx
    spec:                                         # Spec for the container which will run in the Pod
      serviceAccountName: hasher
      shareProcessNamespace: true
      containers:
        - name: nginx
          image: nginx:latest
          stdin: true
          tty: true

        - name: hasher-sidecar
          image: hasher:latest
          imagePullPolicy: Never
          envFrom:
          - secretRef:
              name: hasher-database-secret               # Name of the secret environmental variable file to load
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                 fieldPath: metadata.name
            - name: DEPLOYMENT_TYPE
              value: deployment
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          securityContext:
            capabilities:
              add:
              - SYS_PTRACE
          stdin: true
          tty: true



