apiVersion: v1
kind: Secret
metadata:
  name: hasher-database-secret
type: Opaque
stringData:  # We dont need to worry about converting to base64
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
  POSTGRES_DB: ""

  DB_HOST: hasher-database-svc
  DB_DRIVER: postgres
  DB_USER: ""
  DB_PASSWORD: ""
  DB_NAME: ""
  DB_PORT: "5432"
