# Container image variables
container:
  name: nginx # Container name
  image: nginx:latest # Container image that you deploy to the cluster

containerSidecar:
  name: hasher # Container name
  image: hasher:latest # Container image that you deploy to the cluster

# Name and identifier variables
metadata:
  deploymentName: nginx-hasher-integrity # Set the unique name for deployment schema
  appName: nginx-app # Application name label

# Name of Container Monitor App service account
serviceAccount: hasher # Service account name

# Number of replicas
replicaCount: 1

# Configuration file variables
configMap:
  processName: nginx # Container process name
  mountPath: etc/nginx # Tracked folder path

# Dependency to database "postgresql"
secretName: secret-database-to-integrety-sum # Set the unique name for secret for database

postgresql:
  auth:
    # Authentication data to connect to the database, need to set
    postgresPassword: "1234"
    username: "user"
    password: "1234"
    database: "hashdb"
    postgresqlDataDir: /bitnami/postgresql/data

  primary:
    initdb:
      scripts:
        # Set by the initdb script during initial container startup
        00_init_extensions.sh: |
          #!/bin/sh
          export PGPASSWORD=$POSTGRES_PASSWORD
          psql -w -d $POSTGRES_DB -U $POSTGRES_USER -c "
          CREATE TABLE IF NOT EXISTS hashfiles
          (
          id                BIGSERIAL PRIMARY KEY,
          file_name         VARCHAR NOT NULL,
          full_file_path    TEXT    NOT NULL,
          algorithm         VARCHAR NOT NULL,
          hash_sum          VARCHAR NOT NULL,
          name_deployment   TEXT,
          name_pod          TEXT,
          time_of_creation  VARCHAR (50),
          image_tag         TEXT
          );"
    # Enable security context
    podSecurityContext:
      enabled: false
      fsGroup: ""
    # Enable container security context
    containerSecurityContext:
      enabled: false
      runAsUser: "auto"
    service:
      ## PosgresSQL service type
      type: ClusterIP
      # clusterIP: None
      port: 5432

    persistence:
      # Enable PostgreSQL Primary data persistence using PVC
      enabled: true
      existingClaim: ""
      # mountPath: /bitnami/postgresql - default mountPath
      accessModes:
        - ReadWriteMany
      size: 5Gi

    #Enable security context
    readReplicas:
      podSecurityContext:
        enabled: false
        fsGroup: ""
      containerSecurityContext:
        enabled: false
        runAsUser: "auto"

    # Enable init container that changes the owner and group of the persistent volume
    volumePermissions:
      enabled: false
      securityContext:
        runAsUser: "auto"
